name: '${pluginName}'
version: '${version}'
main: org.yuemi.mmoessence.plugin.EssencePlugin
authors: [${authors}]
contributors: [${contributors}]
api-version: '${apiVersion}'
softdepend: [
  YueMiLibs
]
